language: c
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - build-essential
    - libtool
    - gperf
    #- gcc-4.8
    - gcc-multilib
    - libgdbm-dev:i386
  coverity_scan:
    project:
      name: "perl11/cperl"
      description: "a perl5 with classes, types, compilable, company friendly"
    notification_email: rurban@cpanel.net
    build_command_prepend: "./Configure -des -Dusedevel -Uversiononly -Dprefix=$HOME/cperl"
    build_command: "make -s -j4 ECHO=true"
    branch_pattern: coverity
#cache:
#  apt: true
# needed for trusty gcc-multilib
#before_install:
#  - dpkg --add-architecture i386
#  - apt-get update -qq

# disable the default submodule logic, no .git-rr-cache
git:
  submodules: false
# the other trick would be this:
# replace private SSH URL with the public URL
#before_install:
#  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
#  - git submodule update --init --recursive

os:
  - linux
  - osx

branches:
  only:
    - master
    - /smoke/
    - /coverity/
    - /^maint-/

env:
  matrix:
    - CONFIGURE_OPTION='' XCC='gcc' XBITS=64
    - CONFIGURE_OPTION='-Duse64bitint' XCC="'gcc\ -m32'" XBITS=32
    - CONFIGURE_OPTION='-DDEBUGGING -Duseshrplib' XCC='clang'
    - CONFIGURE_OPTION='-Duse64bitall -Dusethreads -Duselongdouble' XCC='clang'
    - CONFIGURE_OPTION='-Dusethreads -DDEBUGGING -Duse64bitall' XCC='gcc'

matrix:
#  allow_failures:
#    - env: CONFIGURE_OPTION='-Duse64bitint' XCC="'gcc\ -m32'"
  fast_finish: true

#osx:   - CONFIGURE_OPTION='-Duselongdouble -Accflags="-march=corei7 -DPERL_FAKE_SIGNATURE"'
#linux: - CONFIGURE_OPTION='-Duselongdouble -Accflags="-march=native -msse4.2 -DPERL_FAKE_SIGNATURE"'

script:
  - test -n $TRAVIS_TAG && CONFIGURE_OPTION="$CONFIGURE_OPTION -Dusedevel";
    ./Configure -des -Uversiononly -Dcc="$XCC" $CONFIGURE_OPTION -Dprefix=$HOME/cperl/usr
    && make -j4 -s
  - if [ ${TRAVIS_OS_NAME} = "linux" -o -z "`echo $CONFIGURE_OPTION | grep 'DDEBUGGING' 2>/dev/null`" ]; then
      TEST_JOBS=4 make -s -j4 test_harness && make -s install && $HOME/cperl/usr/bin/cperlivp;
    fi

# only the cfgs with XBITS set. at all 4 cfgs: linux64 linux32 osx64 osx32(?)
# windows releases with appveyor. deb, rpm, osx packages done extra at home.
before_deploy:
  - test -z $CONFIGURE_OPTION && test -n $XBITS
    && tar -czvf cperl-${TRAVIS_TAG}-${TRAVIS_OS_NAME}${XBITS}.tar.gz -C $HOME/cperl *

deploy:
  provider: releases
  file: cperl-${TRAVIS_TAG}-${TRAVIS_OS_NAME}${XBITS}.tar.gz
  skip_cleanup: true
  on:
    tags: true

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
